language: java
jdk:
  - openjdk8

before_install:
 - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1
    
script:
  - ./gradlew clean versionInfoFile dist
  - ./gradlew test --info --stacktrace

after_success:
 - ./gradlew jacocoTestReport
 - bash <(curl -s https://codecov.io/bash)
